### ISSUE TITLE
Add role check for API calls

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/tc-billing-account-service#14]
We'll need to make sure we secure the endpoints correctly.  Let's talk about how we handle the role checks for each endpoint...

**Comment by ajefts** [comment]
@skyhit Are we done with this one?

**Comment by skyhit** [comment]
@ajefts check this - https://github.com/topcoder-platform/tc-billing-account-service/blob/dev/service/src/main/java/com/appirio/service/billingaccount/resources/BillingAccountResource.java#L107

we added security check, let me know if need to improve the security check.
