### ISSUE TITLE
Error saving client

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/tc-billing-account-service#20]
When updated an existing client, it's throwing this error:  https://github.com/topcoder-platform/tc-billing-account-service/blob/dev/service/src/main/java/com/appirio/service/billingaccount/manager/ClientManager.java#L121

However, I'm not changing the client name.  I'm simply trying to update an existing client without changing any data.

**Comment by ajefts** [comment]
@skyhit Can you patch this one?

**Comment by skyhit** [comment]
@ajefts is it possible there is another client with the same name? looks like the logic is correct

**Comment by skyhit** [comment]
@ajefts are you testing in dev?
