### ISSUE TITLE
Associate billing account to client

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/tc-billing-account-service#25]

**Comment by ajefts** [comment]
@skyhit How do I associate the billing account to the client?  In the db, it's the client_project_xref table...

**Comment by skyhit** [comment]
@ajefts we are using `client_project` table.

**Comment by skyhit** [comment]
@ajefts  checking the code, when creating billing account, we just create/update a billing account we just deal with `time_oltp:project` table.

**Comment by skyhit** [comment]
so we should use the `customer_number` to find the corresponding client, and add associate with billing account?

**Comment by ajefts** [comment]
No, customer_number should just be a free form text field with no referential integrity.  Think of it like an external reference code.

For mapping a billing account to a client, we should be setting the client_id and project_id in that client_project table.  On the front end, we'd select from a list of clients to set on the billing account.

**Comment by skyhit** [comment]
@ajefts so we need separate api to doing this?

**Comment by ajefts** [comment]
I was thinking it should be part of the create/update calls.  It's always a 1:1 relationship, so we can have a client_id field on the create/update endpoints.  It should also be on the GET endpoints.

**Comment by skyhit** [comment]
defining client_project, means it can be n-n pairing, if it is always 1:1 relationship, we can directly put the client_id in project table.

if we can do like this way, if you want to

**Comment by ajefts** [comment]
Everything is currently using that client_project relationship when we
query it, so we'll need to stay with that.

**Comment by skyhit** [comment]
@ajefts yeah, that is my thought. so I think this https://github.com/topcoder-platform/tc-billing-account-service/blob/dev/swagger.yaml#L476 should be changed to cliend_id or client name?

**Comment by ajefts** [comment]
correct.  client_id
