### ISSUE TITLE
Add challenge budget to the billing account

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/tc-billing-account-service#5]

**Comment by skyhit** [comment]
@ajefts based on database schema, this field is already added, please re-check for dev, qa and prod environments

**Comment by ajefts** [comment]
Yes, we've added this.  I added the column to prod as well so it'll be ready when we deploy.  Thanks.

**Comment by ajefts** [comment]
@skyhit Can you rename the field in the api from "amount" to "budgetAmount"?

**Comment by skyhit** [comment]
@ajefts  this is only related to the API facing part, right?

**Comment by ajefts** [comment]
@skyhit yes

**Comment by skyhit** [comment]
@ajefts please check https://github.com/topcoder-platform/tc-billing-account-service/pull/17
