### ISSUE TITLE
Add billable flag to the billing account.

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/tc-billing-account-service#6]

**Comment by skyhit** [comment]
@ajefts this seems same as https://github.com/appirio-tech/direct-app/issues/209, so basically, we will add a billable flag and make it pass through to save and return ?

**Comment by ajefts** [comment]
@skyhit Yes, please

**Comment by skyhit** [comment]
@ajefts is it required? if not and not passed, what value should we set?

**Comment by ajefts** [comment]
Let's make it required. If null, then treat it as false.

**Comment by skyhit** [comment]
challenge launched - https://www.topcoder.com/direct/contest/detail?projectId=30056728
